### ISSUE TITLE
Integrate package-lint

### ISSUE THREAD

**Issue by DamienCassou** [gonewest818/elisp-lint#19]
What is the relationship with https://github.com/purcell/package-lint? Would it be possible to integrate package-lint to simplify ci configuration?

**Comment by gonewest818** [comment]
Indeed, it does seem like a convergence of the two would be better. Honestly I don't have time to focus on that, and haven't brought it up with Steve either...

**Comment by gonewest818** [comment]
I've started looking at this. While the naive integration isn't that
difficult, it opens up an opportunity to handle another issue #20
which is long overdue. I'm going to address both of these together.
