### ISSUE TITLE
need a summary report

### ISSUE THREAD

**Issue by gonewest818** [gonewest818/elisp-lint#20]
<img width="688" alt="screen shot 2018-04-28 at 10 44 53 am" src="https://user-images.githubusercontent.com/2460918/39399379-6955db64-4ad1-11e8-9eed-b07e9f348b95.png">

**Comment by bbatsov** [comment]
I dream about this every day! 😆

**Comment by gonewest818** [comment]
Finally working on this because it's high time something was done.

Each individual validator will be rewritten to yield a list of
lines/columns containing lint errors. Those line-by-line errors will
then be merged and sorted to produce a summary per file that reads
logically from top-to-bottom.

**Comment by bbatsov** [comment]
@gonewest818 Happy to hear this! I'm still dreaming about those improvements. :D
