### ISSUE TITLE
Ignore certain checks in certain files

### ISSUE THREAD

**Issue by wpcarro** [gonewest818/elisp-lint#28]
Thanks for writing this package!

I'm using a pattern like `*.el`, and I'd like to ignore certain checks, in some files but not in all files. Is this currently possible?

**Comment by gonewest818** [comment]
I handle this by running the tool more than once, with different arguments. A common case I have is that unit tests aren't "packages" so I don't want to run package-lint on those files.

Take a look at the feature described in issue #21 -- the ability to turn off certain checks for certain line ranges. Would that meet your needs?

**Comment by wpcarro** [comment]
> Take a look at the feature described in issue #21 -- the ability to turn off certain checks for certain line ranges. Would that meet your needs?

Short answer: yes.

Thanks for linking to that issue. Let's discuss there!
