### ISSUE TITLE
Use of color in output breaks use of M-x compile usage in that file location "links" are garbled

### ISSUE THREAD

**Issue by illumino** [gonewest818/elisp-lint#30]
Firstly, thanks for developing elisp-lint :-) I have added a "lint" target to my makefile to run elisp-lint.

The addition color support while great, does "break" the filename:linenumber "links" that start each issue, when used with M-x compile output. That is, if I run M-x compile [RETURN] make lint [RETURN], the color sequence at the start of each line stops Emacs 26.1 & 27.1 [the versions I have] from turning [color_seq][filename]:[linenumber] "links" in to valid links, that is, the user is asked to locate  [color_seq][filename] via a file dialog box when clicking on such a link.

With the simple change below, I was able to manually disable color printing and have the output of elisp-lint create clickable links within Emacs, using: M-x compile [RETURN] NO_COLOR=1 make lint [RETURN]

While a programmer, I'm not an Emacs Lisp programmer, so I'll include a working solution below as an example only, rather than creating a pull request - as the approach is possibly simplistic / sub-optimal Emacs lisp. I permanently donate the code below to the elisp-lint project/repository for its maintainers to do with as they please and require no attribution and explicitly forego any cliam of copyright on this code.

Regards,
Peter

PS: I'm still having trouble with .dir-locals.el, in that, settings within it are used by Emacs but seemingly not used by elisp-lint, but I'll do more research and testing before asking formally about that.

```
(defconst elisp-lint--no-color
  (let ((value (getenv-internal "NO_COLOR")))
    (and (stringp value) (> (length value) 0)))
  "Disable color printing via the environment variable NO_COLOR being a non-empty string")

(defun elisp-lint--print (color fmt &rest args)
  "Print output text in COLOR, formatted according to FMT and ARGS."
  (if elisp-lint--no-color
      (progn
	(princ (apply #'format fmt args))
	(terpri))
    (let ((ansi-val (cdr (assoc color elisp-lint--ansi-colors)))
          (cfmt (concat "\u001b[%sm" fmt  "\u001b[0m")))
      (princ (apply #'format cfmt ansi-val args))
      (terpri))))

```

**Comment by gonewest818** [comment]
Thanks for putting this together. How about I create an emacs variable so users can `M-x customize` as they like?
